(add-to-list 'load-path "~/.emacs.d/settings")
(add-to-list 'load-path "~/.emacs.d/libs")

(setq plugin-path "~/.emacs.d/el-get/")
(setq el-get-user-package-directory "~/emacs.d/init")

(defvar root.dir (expand-file-name "~/"))
(defvar emacs.dir (concat root.dir ".emacs.d/"))
(defvar conf.dir (concat emacs.dir "settings/"))
;;(toggle-debug-on-error)

(require 'el-get-settings)
(require 'general-settings)
(require 'yasnippet-settings)
(require 'abbrev-settings)
(require 'magit-settings)
(require 'bookmark-settings)
(require 'org-mode-settings)
(require 'yaml-settings)
(require 'haml-settings)
(require 'auctex-settings)
(require 'ido-settings)
(require 'asciidoc-settings)
(require 'multimarkdown-settings)
(require 'restructuredtext-settings)
(require 'predictive-settings)
(require 'info-settings)
(require 'autocomplete-settings)
(require 'cdet-settings)
(require 'pymacs-settings)
(require 'python-settings)
(require 'cperl-settings)
(require 'cmode-settings)
(require 'ruby-settings)
(require 'java-settings)
(require 'groovy-settings)
(require 'lisp-settings)
(require 'makefile-settings)
(require 'php-settings)
(require 'js-settings)
(require 'html-settings)
(require 'slime-settings)

(load 
    (setq custom-file (expand-file-name "settings/custom.el" user-emacs-directory))
    'noerror)
